import { Product } from "@/types";

export const PRODUCTS_CATALOG: Product[] = [
  {
    id: "prod_spirulina",
    name: "Avira Organic Spirulina 500mg",
    category: "CELLULAR_NUTRITION",
    description: "Pure Blue-Green Microalgae rich in chlorophyll, plant proteins, and antioxidants for natural cellular stamina.",
    netQuantity: "60 Veg Capsules",
    mrp: 450,
    pv: 12,
    tag: "12 PV • High Seller",
    inStock: true,
    imageIcon: "spa",
  },
  {
    id: "prod_tulsi",
    name: "Avira Panch Tulsi Ark Drops",
    category: "IMMUNITY",
    description: "Concentrated liquid extract of 5 sacred Tulsi varieties (Rama, Shyama, Van, Shukla, Surasa) for deep respiratory defense.",
    netQuantity: "30 ml Glass Dropper",
    mrp: 299,
    pv: 8,
    tag: "8 PV • Daily Essential",
    inStock: true,
    imageIcon: "water_drop",
  },
  {
    id: "prod_noni",
    name: "Avira Noni Gold Premium Juice",
    category: "CELLULAR_NUTRITION",
    description: "Enriched with Kokum and Morinda Citrifolia for superior gut detox, cellular regeneration, and joint vitality.",
    netQuantity: "500 ml Bottle",
    mrp: 699,
    pv: 18,
    tag: "18 PV • Vitality Booster",
    inStock: true,
    imageIcon: "medication_liquid",
  },
  {
    id: "prod_curcumin",
    name: "Avira Curcumin Plus 95% Piperine",
    category: "HERBAL_WELLNESS",
    description: "Standardized 95% curcuminoids enhanced with black pepper piperine for 2000% higher bioavailability and anti-inflammatory support.",
    netQuantity: "60 Veg Capsules",
    mrp: 799,
    pv: 20,
    tag: "20 PV • Anti-Inflammatory",
    inStock: true,
    imageIcon: "grain",
  },
  {
    id: "prod_seabuckthorn",
    name: "Avira Sea Buckthorn Immunity Juice",
    category: "IMMUNITY",
    description: "Himalayan superfruit rich in rare Omega-7, Vitamin C, and bioflavonoids for radiant skin and immune resilience.",
    netQuantity: "500 ml Bottle",
    mrp: 899,
    pv: 24,
    tag: "24 PV • Superfood Elixir",
    inStock: true,
    imageIcon: "local_florist",
  },
  {
    id: "prod_omega3",
    name: "Avira Omega-3 Triple Strength",
    category: "CELLULAR_NUTRITION",
    description: "Purified deep-sea fish oil providing 1000mg Omega-3 with 550mg EPA + 350mg DHA for cardiovascular and cognitive longevity.",
    netQuantity: "60 Softgels",
    mrp: 999,
    pv: 28,
    tag: "28 PV • Heart & Brain",
    inStock: true,
    imageIcon: "vital_signs",
  },
  {
    id: "prod_calcium",
    name: "Avira Calcium & Vitamin D3 Bone Fortifier",
    category: "DAILY_CARE",
    description: "Easily absorbable calcium citrate with bioavailable Vitamin D3 and Magnesium for bone density and joint flexibility.",
    netQuantity: "60 Tablets",
    mrp: 420,
    pv: 12,
    tag: "12 PV • Bone Health",
    inStock: true,
    imageIcon: "healing",
  },
  {
    id: "prod_ortho_oil",
    name: "Avira Ortho Relief Ayurvedic Oil",
    category: "HERBAL_WELLNESS",
    description: "Traditional herbal formulation of Nilgiri, Gandhapura, and Mahavishgarbha oils for fast soothing of knee and muscle pain.",
    netQuantity: "100 ml Pump Bottle",
    mrp: 380,
    pv: 10,
    tag: "10 PV • Quick Relief",
    inStock: true,
    imageIcon: "sanitizer",
  },
  {
    id: "prod_aloe_gel",
    name: "Avira Pure Aloe Vera Multi-Purpose Gel",
    category: "DAILY_CARE",
    description: "99% pure cold-pressed organic aloe vera leaf pulp with Vitamin E for skin soothing, sunburn relief, and deep hydration.",
    netQuantity: "200 gm Jar",
    mrp: 320,
    pv: 8,
    tag: "8 PV • Organic Skincare",
    inStock: true,
    imageIcon: "eco",
  },
  {
    id: "prod_diab_care",
    name: "Avira Diabetic Care Karela Jamun Juice",
    category: "HERBAL_WELLNESS",
    description: "Potent blend of Karela, Jamun, Gurmar, and Methi seed extracts to naturally maintain healthy blood glucose levels.",
    netQuantity: "1000 ml Bottle",
    mrp: 1199,
    pv: 35,
    tag: "35 PV • Metabolic Health",
    inStock: true,
    imageIcon: "local_drink",
  },
  {
    id: "prod_collagen",
    name: "Avira Pro-Collagen Youth Booster",
    category: "DAILY_CARE",
    description: "Premium hydrolyzed marine collagen peptides with hyaluronic acid, glutathione, and biotin for firm skin and thick hair.",
    netQuantity: "30 Ready-to-Mix Sachets",
    mrp: 1850,
    pv: 50,
    tag: "50 PV • Premium Luxury",
    inStock: true,
    imageIcon: "diamond",
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS_CATALOG.find((p) => p.id === id);
}

export function getAllProducts(): Product[] {
  return PRODUCTS_CATALOG;
}
